[2021-06-27 20:25:56,154] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: mysqltomongo.export_mysql_customer 2021-06-27T20:25:51.782560+00:00 [queued]>
[2021-06-27 20:25:56,199] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: mysqltomongo.export_mysql_customer 2021-06-27T20:25:51.782560+00:00 [queued]>
[2021-06-27 20:25:56,201] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-27 20:25:56,202] {taskinstance.py:1068} INFO - Starting attempt 1 of 2
[2021-06-27 20:25:56,210] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-27 20:25:56,298] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): export_mysql_customer> on 2021-06-27T20:25:51.782560+00:00
[2021-06-27 20:25:56,319] {standard_task_runner.py:52} INFO - Started process 2853 to run task
[2021-06-27 20:25:56,332] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'mysqltomongo', 'export_mysql_customer', '2021-06-27T20:25:51.782560+00:00', '--job-id', '120', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/mysqlmongo.py', '--cfg-path', '/tmp/tmpqj74rhvs', '--error-file', '/tmp/tmpedav3g_f']
[2021-06-27 20:25:56,369] {standard_task_runner.py:77} INFO - Job 120: Subtask export_mysql_customer
[2021-06-27 20:25:56,666] {logging_mixin.py:104} INFO - Running <TaskInstance: mysqltomongo.export_mysql_customer 2021-06-27T20:25:51.782560+00:00 [running]> on host b69deda3a989
[2021-06-27 20:25:56,857] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=tech@innospark.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mysqltomongo
AIRFLOW_CTX_TASK_ID=export_mysql_customer
AIRFLOW_CTX_EXECUTION_DATE=2021-06-27T20:25:51.782560+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-06-27T20:25:51.782560+00:00
[2021-06-27 20:25:56,859] {logging_mixin.py:104} INFO - Entering export_mysql_to_csv docker-mysql
[2021-06-27 20:25:56,921] {base.py:78} INFO - Using connection to: id: docker-mysql. Host: 172.27.240.1, Port: 3306, Schema: , Login: root, Password: ***, extra: {'charset': 'utf8', 'local_infile': True}
[2021-06-27 20:25:57,003] {python.py:151} INFO - Done. Returned value was: None
[2021-06-27 20:25:57,029] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=mysqltomongo, task_id=export_mysql_customer, execution_date=20210627T202551, start_date=20210627T202556, end_date=20210627T202557
[2021-06-27 20:25:57,151] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-06-27 20:25:57,224] {local_task_job.py:151} INFO - Task exited with return code 0
