[2021-06-27 06:38:36,224] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: example_mysql.create_table_mysql 2021-06-27T06:38:34.524087+00:00 [queued]>
[2021-06-27 06:38:36,275] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: example_mysql.create_table_mysql 2021-06-27T06:38:34.524087+00:00 [queued]>
[2021-06-27 06:38:36,276] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-27 06:38:36,277] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-06-27 06:38:36,290] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-27 06:38:36,328] {taskinstance.py:1087} INFO - Executing <Task(MySqlOperator): create_table_mysql> on 2021-06-27T06:38:34.524087+00:00
[2021-06-27 06:38:36,339] {standard_task_runner.py:52} INFO - Started process 3417 to run task
[2021-06-27 06:38:36,357] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'example_mysql', 'create_table_mysql', '2021-06-27T06:38:34.524087+00:00', '--job-id', '26', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/example_mysql.py', '--cfg-path', '/tmp/tmpzn8m8jn0', '--error-file', '/tmp/tmp8nvd0u_6']
[2021-06-27 06:38:36,368] {standard_task_runner.py:77} INFO - Job 26: Subtask create_table_mysql
[2021-06-27 06:38:36,491] {logging_mixin.py:104} INFO - Running <TaskInstance: example_mysql.create_table_mysql 2021-06-27T06:38:34.524087+00:00 [running]> on host b69deda3a989
[2021-06-27 06:38:36,648] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_mysql
AIRFLOW_CTX_TASK_ID=create_table_mysql
AIRFLOW_CTX_EXECUTION_DATE=2021-06-27T06:38:34.524087+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-06-27T06:38:34.524087+00:00
[2021-06-27 06:38:36,649] {mysql.py:72} INFO - Executing: DROP TABLE Sys.Student;
[2021-06-27 06:38:36,671] {base.py:78} INFO - Using connection to: id: docker-mysql. Host: 192.168.1.27, Port: 3306, Schema: , Login: root, Password: ***, extra: {}
[2021-06-27 06:38:36,716] {dbapi.py:204} INFO - Running statement: DROP TABLE Sys.Student;, parameters: None
[2021-06-27 06:38:36,737] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/mysql/operators/mysql.py", line 74, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 208, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/airflow/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1051, "Unknown table 'Sys.Student'")
[2021-06-27 06:38:36,743] {taskinstance.py:1531} INFO - Marking task as FAILED. dag_id=example_mysql, task_id=create_table_mysql, execution_date=20210627T063834, start_date=20210627T063836, end_date=20210627T063836
[2021-06-27 06:38:36,841] {local_task_job.py:151} INFO - Task exited with return code 1
